apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ekspose-crb
subjects:
- kind: ServiceAccount
  name: default                # Replace with your service account name
  namespace: default     # Replace with your service account's namespace
roleRef:
  kind: ClusterRole
  name: ekspose-cr
  apiGroup: rbac.authorization.k8s.io
