apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ekspose-cr
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch", "create", "delete"]
